file= <_io.TextIOWrapper name='./sat_yaml/test.yamldiag_amsua_n18_ges.yaml' mode='r' encoding='UTF-8'>
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/scratch1/NCEPDEV/da/Kevin.Dougherty/anaconda3/envs/UFO/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/scratch1/NCEPDEV/da/Kevin.Dougherty/anaconda3/envs/UFO/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "../scripts/LAMDA_mapping_workflow.py", line 47, in plotting_func
    plot_dict[config['plot type']](config)
  File "/scratch2/NCEPDEV/fv3-cam/Xiaoyan.Zhang/save/plot/python/code_sprint/pygsi/LAMDA/layer_histogram.py", line 121, in layer_histogram
    metadata,config['outdir'])
  File "/scratch2/NCEPDEV/fv3-cam/Xiaoyan.Zhang/save/plot/python/code_sprint/pygsi/LAMDA/layer_histogram.py", line 43, in _create_hist_layer
    myplt.draw_data(plt_list)
  File "/scratch1/NCEPDEV/da/Cory.R.Martin/Python/conda/local/lib/python3.7/site-packages/emcpy/plots/create_plots.py", line 290, in draw_data
    plot_dict[obj.plottype](obj)
  File "/scratch1/NCEPDEV/da/Cory.R.Martin/Python/conda/local/lib/python3.7/site-packages/emcpy/plots/create_plots.py", line 380, in _histogram
    alpha=plotobj.alpha)
  File "/scratch1/NCEPDEV/da/Kevin.Dougherty/anaconda3/envs/UFO/lib/python3.7/site-packages/matplotlib/__init__.py", line 1438, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/scratch1/NCEPDEV/da/Kevin.Dougherty/anaconda3/envs/UFO/lib/python3.7/site-packages/matplotlib/axes/_axes.py", line 6612, in hist
    raise ValueError(f"The 'color' keyword argument must have one "
ValueError: The 'color' keyword argument must have one color per dataset, but 63 datasets and 1 colors were provided
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "../scripts/LAMDA_mapping_workflow.py", line 110, in <module>
    workflow(data_yaml, plotting_yaml, nprocs, outdir)
  File "../scripts/LAMDA_mapping_workflow.py", line 87, in workflow
    outdir=outdir), work)
  File "/scratch1/NCEPDEV/da/Kevin.Dougherty/anaconda3/envs/UFO/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/scratch1/NCEPDEV/da/Kevin.Dougherty/anaconda3/envs/UFO/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
ValueError: The 'color' keyword argument must have one color per dataset, but 63 datasets and 1 colors were provided
